# Generated by Django 4.1.3 on 2022-11-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
