# Generated by Django 4.1.3 on 2022-11-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                default="1", max_length=150, verbose_name="Full name"
            ),
            preserve_default=False,
        ),
    ]
