# Generated by Django 4.1.3 on 2022-11-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="about"),
        ),
    ]
