# Generated by Django 4.1.3 on 2022-11-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_adv_advimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adv", options={"verbose_name": "Adv", "verbose_name_plural": "Adv"},
        ),
    ]
