# Generated by Django 4.1.3 on 2022-11-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psy_test", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Test",
                "verbose_name_plural": "Tests",
            },
        ),
        migrations.AddField(
            model_name="test", name="order", field=models.IntegerField(default=0),
        ),
    ]
