# Generated by Django 4.1.3 on 2022-11-17 22:01

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "db_table": "chat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "Doctor", "verbose_name_plural": "Doctors"},
        ),
        migrations.AddField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doctor",
            name="about",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterModelTable(name="doctor", table="doctor",),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Text"), ("audio", "Audio")], max_length=10
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("audio", models.FileField(blank=True, null=True, upload_to="audios/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="doctor.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_members",
                        to="doctor.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Member",
                "verbose_name_plural": "Chat Members",
                "db_table": "chat_member",
                "unique_together": {("user", "chat")},
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="members",
            field=models.ManyToManyField(
                through="doctor.ChatMember", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="DoctorRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="doctor.doctor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Rating",
                "verbose_name_plural": "Doctor Ratings",
                "db_table": "doctor_rating",
                "unique_together": {("doctor", "user")},
            },
        ),
    ]
