# Generated by Django 4.1.3 on 2022-11-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_chat_alter_doctor_options_doctor_created_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="chatmember", unique_together=None,),
        migrations.RemoveField(model_name="chatmember", name="chat",),
        migrations.RemoveField(model_name="chatmember", name="user",),
        migrations.RemoveField(model_name="chatmessage", name="chat",),
        migrations.RemoveField(model_name="chatmessage", name="user",),
        migrations.DeleteModel(name="Chat",),
        migrations.DeleteModel(name="ChatMember",),
        migrations.DeleteModel(name="ChatMessage",),
    ]
