# Generated by Django 4.1.3 on 2022-11-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_alter_chatmember_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                ("youtube_link", models.URLField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Video Course",
                "verbose_name_plural": "Video Courses",
                "db_table": "video_course",
                "ordering": ["order", "id"],
            },
        ),
    ]
