# Generated by Django 4.1.3 on 2022-11-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_videocourse"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Video Course Category",
                "verbose_name_plural": "Video Course Categories",
                "db_table": "video_course_category",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="videocourse",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_courses",
                to="doctor.videocoursecategory",
            ),
        ),
    ]
